# CrisisLexT26

Domain Adaptation with Adversarial Training and Graph Embeddings

---

## A. Original description

There are three files per crisis, for each of the following disasters:
- 2012_Colorado_wildfires
- 2012_Costa_Rica_earthquake
- 2012_Guatemala_earthquake
- 2012_Italy_earthquakes
- 2012_Philipinnes_floods
- 2012_Typhoon_Pablo
- 2012_Venezuela_refinery
- 2013_Alberta_floods
- 2013_Australia_bushfire
- 2013_Bohol_earthquake
- 2013_Boston_bombings
- 2013_Brazil_nightclub_fire
- 2013_Colorado_floods
- 2013_Glasgow_helicopter_crash
- 2013_LA_airport_shootings
- 2013_Lac_Megantic_train_crash
- 2013_Manila_floods
- 2013_NY_train_crash
- 2013_Queensland_floods
- 2013_Russia_meteor
- 2013_Sardinia_floods
- 2013_Savar_building_collapse
- 2013_Singapore_haze
- 2013_Spain_train_crash
- 2013_Typhoon_Yolanda
- 2013_West_Texas_explosion


Each directory contains tweets posted during event, organized in two comma-separated values (.csv) files containing tweet-ids for all the tweets filtered for this event, plus the text of the tweets and labels only for the labeled ones. The directory also contains a file with details about the event.

#### Event description file `*-event_description.json`

**Contents:** This file contains location and temporal details about the event, along with a brief categorization, collection size, and the list of keywords used for filtering.

**Data Format:** JSON (check file)

**Top-level fields:** name, time, location, categorization, keywords, size

#### Labeled tweets file `*-tweets_labeled.csv`

**Contents:** This file contains slightly above 1000 tweets labeled by crowdsourcing workers according to *informativeness* (as informative, or not informative), *information type*, and *source*. Each tweet is accompanied by three labels, each being the result of the majority voting among at least 3 crowdsourcing workers.

**Data Format:** One tweet per line with the following comma-separated fields:
*Tweet ID, Tweet Text, Information Source, Information Type, Informativeness*

**Labels:**
The file contains labels provided by crowdsource workers, indicating if the tweet is:

 - *Informativeness:* Related and informative, Related - but not informative, Not related, Not applicable
 - *Information source:* Eyewitness, Government, NGOs, Business, Media, Outsiders, Not applicable
 - *Information type:* Affected individuals, Infrastructure and utilities, Donations and volunteering, Caution and advice, Sympathy and support, Other Useful Information, Not applicable

A description of the labeling process can be found in the reference below.

#### Tweet ids file `*-tweetids_entire_period`

**Contents:** This file contains a list of tweet-ids for all the tweets filtered for this event.

**Data Format:** One tweet per line with the following comma-separated fields:
  *Timestamp, Tweet-ID, Included*

**"Included" field:**
The "Included" file indicates if the tweet was included in the period we analyzed (Y) or not (N). The inclusion/exclusion rule is based on frequency over time as detailed in the reference below.

### Reference

[Olteanu et al. 2015] A. Olteanu, S. Vieweg, C. Castillo. 2015. What to Expect When the Unexpected Happens: Social Media Communications Across Crises. In Proceedings of the ACM 2015 Conference on Computer Supported Cooperative Work and Social Computing (CSCW '15). ACM, Vancouver, BC, Canada.

### Questions/inquiries

For inquiries please contact [Alexandra Olteanu](mailto:alexandra.olteanu@epfl.ch), or Sarah Vieweg, or Carlos Castillo.

## B. Overview

In [1]:
from pathlib import Path
import os

import configuration
from src import dataset_settings

from dotenv import load_dotenv
load_dotenv()
datasets_path = Path(os.getenv("DATASETS_PATH")) / "Datasets"

Loading the `2012_Colorado_wildfires.csv` file

In [2]:
import pandas as pd

dataset_path = datasets_path / 'CrisisLexT26' / 'CrisisLexT26'

filepath = dataset_path / '2012_Colorado_wildfires' / '2012_Colorado_wildfires-tweets_labeled.csv'

if not filepath.exists():
    raise FileNotFoundError(f'Not found: {filepath}')

df = pd.read_csv(filepath)
df.columns = df.columns.str.strip()

In [3]:
df.head()

,Tweet ID,Tweet Text,Information Source,Information Type,Informativeness
0,211040709124440064,#Intern #US #TATTOO #Wisconsin #Ohio #NC #PA #...,Not labeled,Not labeled,Not related
1,211111710294163457,RT @Jack4Ward: Get in on the fun every Thursda...,Not labeled,Not labeled,Not related
2,211157222699433985,Welcome to our newest STUDENTathlete- Reagan B...,Not labeled,Not labeled,Not related
3,211162553659830272,Denver Post: #Colorado governor signs bill cre...,Not labeled,Not labeled,Not related
4,211216962162933761,Pretty sure I'm going to live in Manitou Sprin...,Not labeled,Not labeled,Not related

In [4]:
csv_array = df.values

print(f'Loaded {len(df)} rows from: {filepath}')
print(csv_array[:5])

Loaded 1200 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Colorado_wildfires/2012_Colorado_wildfires-tweets_labeled.csv
[[211040709124440064
  '#Intern #US #TATTOO #Wisconsin #Ohio #NC #PA #Florida #Colorado #Iowa #Nevada #Virginia #NV #mlb Travel Destinations---&gt;http://t.co/TIHBJKF2'
  'Not labeled' 'Not labeled' 'Not related']
 [211111710294163457
  'RT @Jack4Ward: Get in on the fun every Thursday with the @csindependent #FunBrief http://ow.ly/br9Wi #CoSprings #Colorado'
  'Not labeled' 'Not labeled' 'Not related']
 [211157222699433985
  'Welcome to our newest STUDENTathlete- Reagan Biechler\xa0from Colorado Springs (CO) ’13- Baseball. http://t.co/lzeiYMpq'
  'Not labeled' 'Not labeled' 'Not related']
 [211162553659830272
  'Denver Post: #Colorado governor signs bill creating rules for public access to ballots http://t.co/Hmp1wQ8P #opengov'
  'Not labeled' 'Not labeled' 'Not related']
 [211216962162933761
  "Pretty sure I'm going to live in Manitou Springs, CO someday. Maybe live here and work in Colorado Springs?? #theplan"
  'Not labeled' 'Not labeled' 'Not related']]

## C. Preprocess

Combine all train, dev, test files from both events to one

In [5]:
df[df["Informativeness"]=='Not applicable'].head()

,Tweet ID,Tweet Text,Information Source,Information Type,Informativeness
7,211281973870727170,#colorado. Told you its #amazing http://t.co/6...,Not labeled,Not labeled,Not applicable
179,213278894600634369,Forlan no Inter: sites na europa dizem que sim...,Not labeled,Not labeled,Not applicable
374,216741229650649088,RT @jeffestes: #weberfire http://t.co/2pZqhWAS...,Not labeled,Not labeled,Not applicable
404,217018900959858688,Ouvir a torcida do meu #Inter cantando na Ilha...,Not labeled,Not labeled,Not applicable
787,218102289687261184,"Colorado Springs, 2e plus grande ville du Colo...",Not labeled,Not labeled,Not applicable

In [6]:
files = [
    {
        "filename": "2012_Colorado_wildfires/2012_Colorado_wildfires-tweets_labeled.csv",
        "country": "US",
        "event_type": "fire",
        "year": 2012,
    },
    {
        "filename": "2012_Costa_Rica_earthquake/2012_Costa_Rica_earthquake-tweets_labeled.csv",
        "country": "Costa Rica",
        "event_type": "earthquake",
        "year": 2012,
    },
    {
        "filename": "2012_Guatemala_earthquake/2012_Guatemala_earthquake-tweets_labeled.csv",
        "country": "Guatemala",
        "event_type": "earthquake",
        "year": 2012,
    },
    {
        "filename": "2012_Italy_earthquakes/2012_Italy_earthquakes-tweets_labeled.csv",
        "country": "Italy",
        "event_type": "earthquake",
        "year": 2012,
    },
    {
        "filename": "2012_Philipinnes_floods/2012_Philipinnes_floods-tweets_labeled.csv",
        "country": "Philippines",
        "event_type": "flood",
        "year": 2012,
    },
    {
        "filename": "2012_Typhoon_Pablo/2012_Typhoon_Pablo-tweets_labeled.csv",
        "country": "Philippines",
        "event_type": "storm",
        "year": 2012,
    },
    {
        "filename": "2012_Venezuela_refinery/2012_Venezuela_refinery-tweets_labeled.csv",
        "country": "Venezuela",
        "event_type": "incident",
        "year": 2012,
    },
    {
        "filename": "2013_Alberta_floods/2013_Alberta_floods-tweets_labeled.csv",
        "country": "Canada",
        "event_type": "flood",
        "year": 2013,
    },
    {
        "filename": "2013_Australia_bushfire/2013_Australia_bushfire-tweets_labeled.csv",
        "country": "Australia",
        "event_type": "fire",
        "year": 2013,
    },
    {
        "filename": "2013_Bohol_earthquake/2013_Bohol_earthquake-tweets_labeled.csv",
        "country": "Philippines",
        "event_type": "earthquake",
        "year": 2013,
    },
    {
        "filename": "2013_Boston_bombings/2013_Boston_bombings-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Brazil_nightclub_fire/2013_Brazil_nightclub_fire-tweets_labeled.csv",
        "country": "Brazil",
        "event_type": "fire",
        "year": 2013,
    },
    {
        "filename": "2013_Colorado_floods/2013_Colorado_floods-tweets_labeled.csv",
        "country": "US",
        "event_type": "flood",
        "year": 2013,
    },
    {
        "filename": "2013_Glasgow_helicopter_crash/2013_Glasgow_helicopter_crash-tweets_labeled.csv",
        "country": "Scotland",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_LA_airport_shootings/2013_LA_airport_shootings-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Lac_Megantic_train_crash/2013_Lac_Megantic_train_crash-tweets_labeled.csv",
        "country": "Canada",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Manila_floods/2013_Manila_floods-tweets_labeled.csv",
        "country": "Philippines",
        "event_type": "flood",
        "year": 2013,
    },
    {
        "filename": "2013_NY_train_crash/2013_NY_train_crash-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Queensland_floods/2013_Queensland_floods-tweets_labeled.csv",
        "country": "Australia",
        "event_type": "flood",
        "year": 2013,
    },
    {
        "filename": "2013_Russia_meteor/2013_Russia_meteor-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Sardinia_floods/2013_Sardinia_floods-tweets_labeled.csv",
        "country": "US",
        "event_type": "flood",
        "year": 2013,
    },
    {
        "filename": "2013_Savar_building_collapse/2013_Savar_building_collapse-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Singapore_haze/2013_Singapore_haze-tweets_labeled.csv",
        "country": "US",
        "event_type": "haze",
        "year": 2013,
    },
    {
        "filename": "2013_Spain_train_crash/2013_Spain_train_crash-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
    {
        "filename": "2013_Typhoon_Yolanda/2013_Typhoon_Yolanda-tweets_labeled.csv",
        "country": "US",
        "event_type": "storm",
        "year": 2013,
    },
    {
        "filename": "2013_West_Texas_explosion/2013_West_Texas_explosion-tweets_labeled.csv",
        "country": "US",
        "event_type": "incident",
        "year": 2013,
    },
]

In [7]:
df_list = []

for file in files:
    filename = file["filename"]
    filepath = dataset_path / filename
    if not filepath.exists():
        print(f"Not found: {filepath}")
        continue

    df = pd.read_csv(filepath)
    df.columns = df.columns.str.strip()

    # remove `'Not applicable'` in `Informativeness` column
    df = df[df["Informativeness"] != "Not applicable"]

    df.rename(columns={"Tweet ID": "tweet_id"}, inplace=True)
    df.rename(columns={"Tweet Text": "tweet_text"}, inplace=True)
    df["event_type"] = file["event_type"]
    df["country"] = file["country"]
    df["year"] = file["year"]

    # *Informativeness:* Related and informative, Related - but not informative, Not related, Not applicable
    df["relevant"] = df["Informativeness"].apply(lambda x: False if x == "Not related" else True)
    df['file_name'] = filename
    # Store other metadata as JSON text in `meta`.
    df["meta"] = df.apply(
        lambda row: {
            "Information Source": row["Information Source"],
            "Information Type": row["Information Type"],
            "Informativeness": row["Informativeness"],
        },
        axis=1,
    )
    drop_cols = ["Information Source", "Information Type", "Informativeness"]
    df.drop(columns=drop_cols, inplace=True)
    print(f"Loaded {len(df)} rows from: {filepath}")
    df_list.append(df)

# ignore_index=True creates clean, sequential row numbers
merged_df = pd.concat(df_list, ignore_index=True)
merged_df.head()

Loaded 1191 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Colorado_wildfires/2012_Colorado_wildfires-tweets_labeled.csv
Loaded 1308 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Costa_Rica_earthquake/2012_Costa_Rica_earthquake-tweets_labeled.csv
Loaded 1048 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Guatemala_earthquake/2012_Guatemala_earthquake-tweets_labeled.csv
Loaded 990 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Italy_earthquakes/2012_Italy_earthquakes-tweets_labeled.csv
Loaded 994 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Philipinnes_floods/2012_Philipinnes_floods-tweets_labeled.csv
Loaded 975 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Typhoon_Pablo/2012_Typhoon_Pablo-tweets_labeled.csv
Loaded 997 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2012_Venezuela_refinery/2012_Venezuela_refinery-tweets_labeled.csv
Loaded 997 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Alberta_floods/2013_Alberta_floods-tweets_labeled.csv
Loaded 1191 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Australia_bushfire/2013_Australia_bushfire-tweets_labeled.csv
Loaded 1000 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Bohol_earthquake/2013_Bohol_earthquake-tweets_labeled.csv
Loaded 948 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Boston_bombings/2013_Boston_bombings-tweets_labeled.csv
Loaded 995 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Brazil_nightclub_fire/2013_Brazil_nightclub_fire-tweets_labeled.csv
Loaded 995 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Colorado_floods/2013_Colorado_floods-tweets_labeled.csv
Loaded 1095 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Glasgow_helicopter_crash/2013_Glasgow_helicopter_crash-tweets_labeled.csv
Loaded 999 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_LA_airport_shootings/2013_LA_airport_shootings-tweets_labeled.csv
Loaded 997 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Lac_Megantic_train_crash/2013_Lac_Megantic_train_crash-tweets_labeled.csv
Loaded 968 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Manila_floods/2013_Manila_floods-tweets_labeled.csv
Loaded 999 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_NY_train_crash/2013_NY_train_crash-tweets_labeled.csv
Loaded 1180 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Queensland_floods/2013_Queensland_floods-tweets_labeled.csv
Loaded 1404 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Russia_meteor/2013_Russia_meteor-tweets_labeled.csv
Loaded 994 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Sardinia_floods/2013_Sardinia_floods-tweets_labeled.csv
Loaded 1216 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Savar_building_collapse/2013_Savar_building_collapse-tweets_labeled.csv
Loaded 979 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Singapore_haze/2013_Singapore_haze-tweets_labeled.csv
Loaded 997 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Spain_train_crash/2013_Spain_train_crash-tweets_labeled.csv
Loaded 1011 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_Typhoon_Yolanda/2013_Typhoon_Yolanda-tweets_labeled.csv
Loaded 976 rows from: /Users/nhut/Library/CloudStorage/GoogleDrive-dhnhut@gmail.com/Shared drives/Nhut - Disaster on Social Media - COMPSCI 792 Research Project/Datasets/CrisisLexT26/CrisisLexT26/2013_West_Texas_explosion/2013_West_Texas_explosion-tweets_labeled.csv

,tweet_id,tweet_text,event_type,country,year,relevant,file_name,meta
0,211040709124440064,#Intern #US #TATTOO #Wisconsin #Ohio #NC #PA #...,fire,US,2012,False,2012_Colorado_wildfires/2012_Colorado_wildfire...,"{'Information Source': 'Not labeled', 'Informa..."
1,211111710294163457,RT @Jack4Ward: Get in on the fun every Thursda...,fire,US,2012,False,2012_Colorado_wildfires/2012_Colorado_wildfire...,"{'Information Source': 'Not labeled', 'Informa..."
2,211157222699433985,Welcome to our newest STUDENTathlete- Reagan B...,fire,US,2012,False,2012_Colorado_wildfires/2012_Colorado_wildfire...,"{'Information Source': 'Not labeled', 'Informa..."
3,211162553659830272,Denver Post: #Colorado governor signs bill cre...,fire,US,2012,False,2012_Colorado_wildfires/2012_Colorado_wildfire...,"{'Information Source': 'Not labeled', 'Informa..."
4,211216962162933761,Pretty sure I'm going to live in Manitou Sprin...,fire,US,2012,False,2012_Colorado_wildfires/2012_Colorado_wildfire...,"{'Information Source': 'Not labeled', 'Informa..."

In [8]:
merged_df.to_csv( 'datasets/CrisisLexT26.csv', index=False)